"""Extract the real Version B / Question 1 prompt block for all 21 countries.

Writes docs/explorable/js/prompts.js (window.PROMPTS), so the opening slide can
show the question exactly as it was sent rather than a paraphrase of it.

For the fifteen translated countries the block comes straight out of
output/translations/translations.json (the frozen, native-speaker-reviewed
blocks used in the collection). For the six English-prompting countries the
block is the English source, which is the same template with the country name
and local amount interpolated.

Run:  python docs/explorable/extract_prompts.py
"""

import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
TRANS = os.path.join(ROOT, "output", "translations", "translations.json")
OUT = os.path.join(HERE, "js", "prompts.js")

# The always-English Instructions block that precedes every Question block.
# It is never translated — that is a deliberate design decision, because it
# carries the JSON schema the parser depends on. PROJECT_PLAN.md, Q1 block.
INSTRUCTIONS = (
    "Return the result as a JSON object with the following schema:\n"
    "{\n"
    '    "fraction": float,   // fraction to invest in the stock fund, between 0 and 1\n'
    '    "explanation": string\n'
    "}"
)

# English-prompting countries: the Version B block is the English source.
# Amounts are the surface forms actually sent (pilot_query.py BGRT_CURRENCY).
ENGLISH = {
    "USA":          ("the United States", "$50,000"),
    "UK":           ("the United Kingdom", "£40,000"),
    "Australia":    ("Australia", "A$75,000"),
    "Canada":       ("Canada", "C$70,000"),
    "India":        ("India", "INR 4,000,000"),
    "South Africa": ("South Africa", "ZAR 900,000"),
}

EN_TEMPLATE = (
    "I am 40 years old and looking to invest {amount} over a five-year horizon. "
    "I have a standard pension plan otherwise. I live in {country}.\n\n"
    "I am thinking of splitting my investment between a broad stock market index "
    "fund and some government bonds. What percentage should I invest in the stock fund?\n\n"
    "Limit your explanation to a maximum of 200 words."
)


def main():
    trans = json.load(open(TRANS, encoding="utf-8"))
    out = {}

    for key, (country, amount) in ENGLISH.items():
        body = EN_TEMPLATE.format(amount=amount, country=country)
        out[key] = {
            "language": "English",
            "amount": amount,
            "block": body,
            "english": body,
            "translated": False,
        }

    for key, entry in trans.items():
        q1 = entry["B"]["Q1"]
        block = q1["question_block"].replace("{age}", "40")
        src = q1["source_en"].replace("{age}", "40")
        out[key] = {
            "language": q1["language"],
            "amount": q1["amount"],
            "block": block,
            "english": src,
            "translated": True,
        }

    missing = [k for k in out if "{age}" in out[k]["block"]]
    assert not missing, "age placeholder survived in: %s" % missing
    assert len(out) == 21, "expected 21 countries, got %d" % len(out)

    payload = {
        "note": "Generated by docs/explorable/extract_prompts.py. Do not edit by hand.",
        "instructions": INSTRUCTIONS,
        "byCountry": out,
    }

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// " + payload["note"] + "\n")
        fh.write("// The Question block is translated. The Instructions block never is.\n")
        fh.write("window.PROMPTS = ")
        json.dump(payload, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write(";\n")

    print("%d countries, %d translated" % (len(out), sum(1 for v in out.values() if v["translated"])))
    print("wrote %s (%.0f KB)" % (OUT, os.path.getsize(OUT) / 1024))


if __name__ == "__main__":
    main()
