"""Extract the response distributions the explorable needs from the staged collection.

Reads output/analysis_data/clean.csv (the pipeline's cleaned real collection) and writes
docs/explorable/js/responses.js, a plain <script> file defining window.RESPONSES.

Everything else in the explorable comes from the paper's tables of record and is
transcribed by hand into js/data.js. This script covers only the things that need the
raw rows: per-country response histograms, the country-by-model cell means, and the
by-age histograms.

Run:  python docs/explorable/extract_data.py
"""

import csv
import json
import os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(ROOT, "output", "analysis_data", "clean.csv")
OUT = os.path.join(HERE, "js", "responses.js")

MODEL_LABEL = {
    "anthropic/claude-haiku-4.5": "Claude 4.5 Haiku",
    "anthropic/claude-opus-4.6": "Claude 4.6 Opus",
    "anthropic/claude-opus-4.8": "Claude 4.8 Opus",
    "anthropic/claude-sonnet-4.6": "Claude 4.6 Sonnet",
    "deepseek/deepseek-v4-flash": "DeepSeek V4 Flash",
    "deepseek/deepseek-v4-pro": "DeepSeek V4 Pro",
    "google/gemini-3-flash-preview": "Gemini 3 Flash",
    "google/gemini-3.1-pro-preview": "Gemini 3.1 Pro",
    "google/gemini-3.5-flash": "Gemini 3.5 Flash",
    "mistralai/mistral-medium-3-5": "Mistral Medium 3.5",
    "openai/gpt-5-mini": "GPT-5-mini",
    "openai/gpt-5.5": "GPT-5.5",
    "x-ai/grok-4.3": "Grok 4.3",
}


def bucket(x):
    """Snap to the nearest percentage point. Responses are multiples of 5 anyway."""
    return int(round(x * 100))


def main():
    # country -> {pct: count}      primary cell, Q1 / B / age 40
    hist = defaultdict(lambda: defaultdict(int))
    # (country, model) -> [sum, n]
    cell = defaultdict(lambda: [0.0, 0])
    # age -> {pct: count}          pooled over countries, Q1 / B
    by_age = defaultdict(lambda: defaultdict(int))
    # country -> {pct: count}      Q1 / C / age 40, for the version toggle
    hist_c = defaultdict(lambda: defaultdict(int))
    # Bgrt treatment cell -> [sum, n]
    bgrt = defaultdict(lambda: [0.0, 0])

    with open(SRC, encoding="utf-8", newline="") as fh:
        for row in csv.DictReader(fh):
            if row["is_refusal"] in ("1", "True", "TRUE"):
                continue
            if row["truncated"] in ("1", "True", "TRUE"):
                continue
            raw = row["fraction"]
            if raw in ("", ".", "NA"):
                continue
            frac = float(raw)
            country, ver, q, age = (
                row["country"], row["prompt_version"], row["question"], row["age"],
            )

            if q != "Q1":
                continue

            if ver == "B":
                by_age[age][bucket(frac)] += 1
                if age == "40":
                    hist[country][bucket(frac)] += 1
                    cell[(country, row["model"])][0] += frac
                    cell[(country, row["model"])][1] += 1
            elif ver == "C" and age == "40":
                hist_c[country][bucket(frac)] += 1
            elif ver == "Bgrt" and age == "40":
                key = "|".join([
                    row["risk_aversion_stated"] or "none",
                    row["pension_stated"] or "none",
                    row["horizon_stated"] or "none",
                ])
                bgrt[key][0] += frac
                bgrt[key][1] += 1

    countries = sorted(hist)
    models = sorted({m for _, m in cell})

    grid = {}
    for c in countries:
        grid[c] = {}
        for m in models:
            s, n = cell[(c, m)]
            grid[c][MODEL_LABEL.get(m, m)] = round(s / n, 4) if n else None

    payload = {
        "note": "Generated by docs/explorable/extract_data.py from "
                "output/analysis_data/clean.csv. Do not edit by hand.",
        "hist_b40": {c: dict(sorted(hist[c].items())) for c in countries},
        "hist_c40": {c: dict(sorted(hist_c[c].items())) for c in sorted(hist_c)},
        "hist_by_age": {a: dict(sorted(by_age[a].items())) for a in sorted(by_age)},
        "grid": grid,
        "models": [MODEL_LABEL.get(m, m) for m in models],
        "bgrt": {k: [round(v[0] / v[1], 4), v[1]] for k, v in sorted(bgrt.items()) if v[1]},
    }

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// " + payload["note"].replace("\n", "\n// ") + "\n")
        fh.write("window.RESPONSES = ")
        json.dump(payload, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write(";\n")

    n_primary = sum(sum(v.values()) for v in payload["hist_b40"].values())
    print(f"countries: {len(countries)}  models: {len(models)}")
    print(f"primary cell N: {n_primary}")
    print(f"bgrt cells: {len(payload['bgrt'])}")
    print(f"wrote {OUT} ({os.path.getsize(OUT) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
