"""Extract the per-model country contrasts into js/bymodel.js.

Source of record: output/tables/check_q1_country_by_model.csv, written by the
Stata pipeline. One row per non-US country, one column per model, holding the
value of that country's contrast against the US baseline estimated within that
single model. The `share_negative` column is the fraction of models for which
the contrast is negative.

This is what makes the clustering argument visible: the study treats the
thirteen models as the sample, and these are the thirteen observations.

Run:  python docs/explorable/extract_bymodel.py
"""

import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(ROOT, "output", "tables", "check_q1_country_by_model.csv")
OUT = os.path.join(HERE, "js", "bymodel.js")

LABEL = {
    "anthropic/claude-haiku-4.5": "Claude 4.5 Haiku",
    "anthropic/claude-opus-4.6": "Claude 4.6 Opus",
    "anthropic/claude-opus-4.8": "Claude 4.8 Opus",
    "anthropic/claude-sonnet-4.6": "Claude 4.6 Sonnet",
    "deepseek/deepseek-v4-flash": "DeepSeek V4 Flash",
    "deepseek/deepseek-v4-pro": "DeepSeek V4 Pro",
    "google/gemini-3-flash-preview": "Gemini 3 Flash",
    "google/gemini-3.1-pro-preview": "Gemini 3.1 Pro",
    "google/gemini-3.5-flash": "Gemini 3.5 Flash",
    "mistralai/mistral-medium-3-5": "Mistral Medium 3.5",
    "openai/gpt-5-mini": "GPT-5-mini",
    "openai/gpt-5.5": "GPT-5.5",
    "x-ai/grok-4.3": "Grok 4.3",
}


def main():
    rows = list(csv.DictReader(open(SRC, encoding="utf-8")))
    slugs = [k for k in rows[0] if k not in ("country", "pooled_mean", "share_negative")]

    out = {}
    for r in rows:
        out[r["country"]] = {
            "byModel": {LABEL[s]: round(float(r[s]) * 100, 2) for s in slugs},
            "pooled": round(float(r["pooled_mean"]) * 100, 2),
            "shareNegative": round(float(r["share_negative"]), 4),
        }

    payload = {
        "note": "Generated by docs/explorable/extract_bymodel.py from "
                "output/tables/check_q1_country_by_model.csv. Do not edit by hand. "
                "Values are percentage points against the US baseline, within model.",
        "models": [LABEL[s] for s in slugs],
        "byCountry": out,
    }

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// " + payload["note"] + "\n")
        fh.write("window.BYMODEL = ")
        json.dump(payload, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write(";\n")

    print("%d countries, %d models" % (len(out), len(slugs)))
    br = out["Brazil"]
    n_neg = sum(1 for v in br["byModel"].values() if v < 0)
    print("Brazil: pooled %.1f pp, %d of %d models negative (share_negative %.4f)"
          % (br["pooled"], n_neg, len(slugs), br["shareNegative"]))


if __name__ == "__main__":
    main()
